name: 'Develop Workflow'

on:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies    
        run: npm ci

      - name: Run Lint  
        run: npx eslint --ext .js,.jsx src/ --fix-dry-run

      - name: Run Tests
        run: npm test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Build
        run: npm run build --if-present

  preparetag:
      name: Prepare release tag
      needs: lint-test
      runs-on: ubuntu-latest
      outputs:
        sha_output: ${{ steps.short_sha_generator.outputs.SHORT_SHA }}
      steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: Get short SHA
          id: short_sha_generator
          run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  tag-image:
    needs: preparetag
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: astb01/hello-world-app
          tags: latest, ${{ needs.preparetag.outputs.sha_output }}-SNAPSHOT
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}